### ISSUE TITLE
Images not saving?

### ISSUE THREAD

**Issue by Esselans** [Tunous/Dank#19]
Anyone else does have the 'image saved' notification but no image is saved whatsoever? I have no crash or errors.

I've tested on master branch

**Comment by dotvhs** [comment]
For me images are being saved in the Dank folder on my phone, but i can't open them from the notification, gallery app does start but doesn't show the image downloaded.

**Comment by saket** [comment]
This isn't working on my phone either. Looks like something broke recently. I'm using Android 9.0 Pie.

**Comment by Esselans** [comment]
@saket @dotvhs I've committed patch #20 

Can you take a look at it?
