### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by Tunous** [Tunous/Dank#31]
On Android 8, login flow doesn't work. Attempting to login through webview never redirects to page with input for 2 factor auth code.

**Comment by Tunous** [comment]
Perhaps there were changes in Android related to WebView which broke login? By rewriting the code to redirect to browser instead I was able to login successfully.

**Comment by saket** [comment]
I've noticed this happening with other Reddit apps too. They suggest entering the 2FA in the password field or something. Not sure where the problem is.
