### ISSUE TITLE
Splash screen on startup

### ISSUE THREAD

**Issue by killoid** [Tunous/Dank#38]
the splashscreen showing dank's logo at startup looks ugly imo. it will look better & load the app faster if it is removed.

**Comment by Esselans** [comment]
Look #8 for logo ideas

**Comment by Tunous** [comment]
Removing it wouldn't make the app load faster, it appears only for a split second. In my opinion it's much better than seeing plain dark screen.

**Comment by Esselans** [comment]
I agree on keeping the splash screen but improving the logo. Besides that screen only is visible during a cold start of the app.

**Comment by Tunous** [comment]
Closing because we are not going to remove splash screen.
